// User-uploaded images added from the review UI. Three destinations:
//  - a brand-new tile goes straight into the real Tile/tiles/ pool (it's
//    just a flat folder of photos, safe to extend — never overwrites).
//  - a photo for an EXISTING fixture row goes into autoboard's OWN local
//    overlay (uploaded-images/<rowId>/), never into Master_Library_Build —
//    that tree is machine-generated by build_library.py and this tool
//    doesn't touch it, same principle as tile-assignments.json/notes.json.
//  - a BRAND-NEW fixture item (no manifest row at all — the room-library
//    parity gap with tiles) goes into custom-items/<room>/<id>/, its own
//    small local library with a name/brand/notes record alongside the photo.
// withUploads() layers the row-photo overlay in front of any base image
// resolver so both `plan` and the review server see uploaded photos
// consistently.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { tileLibraryDir } from "./tiles.mjs";

const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const ALLOWED_UPLOAD_MIME = { "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp" };
export const MAX_UPLOAD_BYTES = 20 * 1024 * 1024;

export function uploadsRootDir(root) {
  return root ?? path.join(import.meta.dirname, "..", "uploaded-images");
}

export function uploadedImagesFor(rowId, root) {
  const dir = path.join(uploadsRootDir(root), String(rowId));
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()))
    .sort()
    .map((name) => path.join(dir, name));
}

// Wraps a base resolveImages(rowId) so an uploaded photo takes over as the
// row's image once one exists, falling back to the base resolver otherwise.
export function withUploads(baseResolveImages, root) {
  return (rowId) => {
    const uploaded = uploadedImagesFor(rowId, root);
    return uploaded.length ? uploaded : baseResolveImages(rowId);
  };
}

export function isValidTileCode(code) {
  return /^[A-Z]{2}\d+$/.test(code);
}

export function sanitizeNamePart(value) {
  const cleaned = String(value ?? "").trim().replace(/\s+/g, "_").replace(/[^A-Za-z0-9._-]+/g, "");
  return cleaned.slice(0, 80) || "image";
}

// Validates and decodes a client-submitted { mimeType, dataBase64 } upload.
// The extension is derived from the validated mime type, never trusted from
// a client-supplied filename.
export function decodeUploadedImage({ mimeType, dataBase64 }) {
  const ext = ALLOWED_UPLOAD_MIME[mimeType];
  if (!ext) throw Object.assign(new Error("Images must be JPEG, PNG, or WebP."), { status: 400 });
  if (!dataBase64) throw Object.assign(new Error("No image data received."), { status: 400 });
  const buffer = Buffer.from(dataBase64, "base64");
  if (buffer.length === 0) throw Object.assign(new Error("The uploaded image is empty."), { status: 400 });
  if (buffer.length > MAX_UPLOAD_BYTES) throw Object.assign(new Error("Images must be under 20 MB."), { status: 400 });
  return { buffer, ext };
}

export async function saveUploadedRowImage(rowId, buffer, ext, root) {
  const dir = path.join(uploadsRootDir(root), String(rowId));
  await mkdir(dir, { recursive: true });
  const filePath = path.join(dir, `${Date.now()}${ext}`);
  await writeFile(filePath, buffer);
  return filePath;
}

// Never overwrites — a code/name collision is rejected so an accidental
// re-upload can't silently replace an existing real tile photo.
export async function saveUploadedTileImage(libraryRoot, code, materialName, buffer, ext) {
  const dir = tileLibraryDir(libraryRoot);
  const filename = `${code}_${sanitizeNamePart(materialName)}${ext}`;
  const filePath = path.join(dir, filename);
  if (existsSync(filePath)) {
    throw Object.assign(new Error(`A file named "${filename}" already exists in the tile pool.`), { status: 400 });
  }
  await mkdir(dir, { recursive: true });
  await writeFile(filePath, buffer);
  return filePath;
}

export function customItemsRootDir(root) {
  return root ?? path.join(import.meta.dirname, "..", "custom-items");
}

function customItemsRoomDir(roomKeyValue, root) {
  return path.join(customItemsRootDir(root), sanitizeNamePart(roomKeyValue));
}

// Every brand-new (not-in-the-manifest) item added for a room — a small
// local library parallel to a room's real Smartsheet rows.
export function customItemsForRoom(roomKeyValue, root) {
  const dir = customItemsRoomDir(roomKeyValue, root);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((id) => existsSync(path.join(dir, id, "meta.json")))
    .sort()
    .map((id) => {
      const itemDir = path.join(dir, id);
      const meta = JSON.parse(readFileSync(path.join(itemDir, "meta.json"), "utf8"));
      const photo = readdirSync(itemDir).find((name) => IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase()));
      return {
        id,
        name: meta.name ?? "",
        brand: meta.brand ?? "",
        notes: meta.notes ?? "",
        imagePath: photo ? path.join(itemDir, photo) : null,
      };
    });
}

export async function saveCustomItem(roomKeyValue, { name, brand, notes }, buffer, ext, root) {
  const id = `custom-${Date.now()}`;
  const dir = path.join(customItemsRoomDir(roomKeyValue, root), id);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, `photo${ext}`), buffer);
  await writeFile(
    path.join(dir, "meta.json"),
    JSON.stringify({ name, brand: brand ?? "", notes: notes ?? "", createdAt: new Date().toISOString() }, null, 2),
  );
  return { id, name, brand: brand ?? "", notes: notes ?? "", imagePath: path.join(dir, `photo${ext}`) };
}
